# Generated by Django 3.1.1 on 2020-09-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsfModuleManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=100, verbose_name='模块名')),
                ('title', models.CharField(max_length=100, verbose_name='模块中文译名')),
                ('intro', models.TextField(verbose_name='模块介绍')),
                ('options', models.TextField(verbose_name='模块选项翻译')),
            ],
            options={
                'db_table': 'msf_module_manual',
            },
        ),
    ]
