# Generated by Django 3.1.1 on 2020-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msfmodulemanual',
            name='intro',
            field=models.TextField(default='', verbose_name='模块介绍'),
        ),
        migrations.AlterField(
            model_name='msfmodulemanual',
            name='options',
            field=models.TextField(null=True, verbose_name='模块选项翻译'),
        ),
    ]
