# Generated by Django 3.1.1 on 2020-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20200929_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='msfmodulemanual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='msfmodulemanual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
