# Generated by Django 3.1.1 on 2020-09-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_auto_20200929_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_source', models.TextField(verbose_name='英文')),
                ('zh_target', models.TextField(verbose_name='翻译')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'translation_base',
            },
        ),
    ]
