# Generated by Django 3.1.1 on 2020-11-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_focuskeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='菜单文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('type', models.CharField(max_length=50, verbose_name='右键菜单类型')),
                ('addition', models.TextField(null=True, verbose_name='额外选项')),
                ('pid', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='kb.contextmenu')),
            ],
        ),
    ]
