# Generated by Django 3.1.1 on 2020-11-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_contextmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextmenu',
            name='is_autorun',
            field=models.BooleanField(default=False, verbose_name='是否直接自动执行'),
        ),
        migrations.AlterField(
            model_name='contextmenu',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
