# Generated by Django 3.1.1 on 2020-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_auto_20201104_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='脚本标题')),
                ('description', models.TextField(default='', verbose_name='脚本介绍')),
                ('filename', models.CharField(max_length=100, verbose_name='脚本文件名')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'resource_scripts',
            },
        ),
    ]
