# Generated by Django 3.1.1 on 2020-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_resourcescript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescript',
            name='filename',
            field=models.CharField(max_length=100, unique=True, verbose_name='脚本文件名'),
        ),
    ]
