# Generated by Django 3.1.1 on 2020-09-07 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='模块名')),
                ('fullname', models.CharField(db_index=True, max_length=100, verbose_name='模块完整名')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, verbose_name='别名'), size=None)),
                ('disclosure_date', models.CharField(max_length=30, null=True, verbose_name='披露时间')),
                ('rank', models.IntegerField(null=True, verbose_name='评分')),
                ('type', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('author', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='作者')),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='参考资料')),
                ('platform', models.CharField(blank=True, max_length=250, verbose_name='平台')),
                ('arch', models.CharField(blank=True, max_length=250, verbose_name='架构')),
                ('rport', models.IntegerField(null=True, verbose_name='远端端口')),
                ('mod_time', models.CharField(max_length=30, null=True, verbose_name='披露时间')),
                ('ref_name', models.CharField(db_index=True, max_length=100, verbose_name='模块引用名')),
                ('path', models.CharField(max_length=100, verbose_name='模块路径')),
                ('is_install_path', models.BooleanField(default=False)),
                ('targets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None, verbose_name='目标平台')),
                ('info_html', models.TextField(null=True, verbose_name='详细介绍')),
                ('compatible_payloads', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None, verbose_name='exp兼容payload')),
                ('options', models.JSONField(null=True, verbose_name='模块选项')),
            ],
        ),
    ]
