# Generated by Django 3.1.1 on 2020-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfjsonrpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='mod_time',
            field=models.CharField(max_length=30, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ref_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='模块标识'),
        ),
    ]
