# Generated by Django 3.1.1 on 2020-11-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msfjsonrpc', '0002_auto_20200917_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModAutoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(null=True, verbose_name='配置项')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开给其他人使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
