# Generated by Django 3.1.1 on 2020-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfjsonrpc', '0003_modautoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='modautoconfig',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
    ]
