# Generated by Django 3.1.1 on 2020-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfjsonrpc', '0004_modautoconfig_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='info',
            field=models.JSONField(null=True, verbose_name='详细信息'),
        ),
    ]
