# Generated by Django 3.1.1 on 2020-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='info', max_length=10, verbose_name='日志等级'),
        ),
    ]
